// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdY_3ket48Kx0LpHbtcUkXQBZJcdKX6s',
    appId: '1:761509260897:web:1d8d5b0db8c61261f48420',
    messagingSenderId: '761509260897',
    projectId: 'rfid-door-lock-dc802',
    authDomain: 'rfid-door-lock-dc802.firebaseapp.com',
    databaseURL: 'https://rfid-door-lock-dc802-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-door-lock-dc802.appspot.com',
    measurementId: 'G-K9V4FB62CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfkai34zEt2rfh5H0hHO_caZsACzwi-AU',
    appId: '1:761509260897:android:dba48616ca359692f48420',
    messagingSenderId: '761509260897',
    projectId: 'rfid-door-lock-dc802',
    databaseURL: 'https://rfid-door-lock-dc802-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-door-lock-dc802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRILUmmneI1mJX3Gbk2c6b2BzA1svhNKI',
    appId: '1:761509260897:ios:c0db51805ac35cdaf48420',
    messagingSenderId: '761509260897',
    projectId: 'rfid-door-lock-dc802',
    databaseURL: 'https://rfid-door-lock-dc802-default-rtdb.firebaseio.com',
    storageBucket: 'rfid-door-lock-dc802.appspot.com',
    iosClientId: '761509260897-p1osecgbrh4fh9bvpg76ptoat73uesfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.goKart',
  );
}
